[package]
name = "replay-buffer"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
env_logger = { workspace = true }
libobs = { workspace = true }
libobs-wrapper = { workspace = true }
libobs-simple = { workspace = true }

[lints]
workspace = true
